export const users = [
  {
    key: "1",
    name: "Tony Reichert",
    description: "CEO",
    status: "Active",
  },
  {
    key: "2",
    name: "Zoey Lang",
    description: "Technical Lead",
    status: "Paused",
  },
  {
    key: "3",
    name: "Jane Fisher",
    description: "Senior Developer",
    status: "Active",
  },
  {
    key: "4",
    name: "William Howard",
    description: "Community Manager",
    status: "Vacation",
  },
  {
    key: "5",
    name: "Emily Collins",
    description: "Marketing Manager",
    status: "Active",
  },
  {
    key: "6",
    name: "Brian Kim",
    description: "Product Manager",
    status: "Active",
  },
  {
    key: "7",
    name: "Laura Thompson",
    description: "UX Designer",
    status: "Active",
  },
  {
    key: "8",
    name: "Michael Stevens",
    description: "Data Analyst",
    status: "Paused",
  },
  {
    key: "9",
    name: "Sophia Nguyen",
    description: "Quality Assurance",
    status: "Active",
  },
  {
    key: "10",
    name: "James Wilson",
    description: "Front-end Developer",
    status: "Vacation",
  },
  {
    key: "11",
    name: "Ava Johnson",
    description: "Back-end Developer",
    status: "Active",
  },
  {
    key: "12",
    name: "Isabella Smith",
    description: "Graphic Designer",
    status: "Active",
  },
  {
    key: "13",
    name: "Oliver Brown",
    description: "Content Writer",
    status: "Paused",
  },
  {
    key: "14",
    name: "Lucas Jones",
    description: "Project Manager",
    status: "Active",
  },
  {
    key: "15",
    name: "Grace Davis",
    description: "HR Manager",
    status: "Active",
  },
  {
    key: "16",
    name: "Elijah Garcia",
    description: "Network Administrator",
    status: "Active",
  },
  {
    key: "17",
    name: "Emma Martinez",
    description: "Accountant",
    status: "Vacation",
  },
  {
    key: "18",
    name: "Benjamin Lee",
    description: "Operations Manager",
    status: "Active",
  },
  {
    key: "19",
    name: "Mia Hernandez",
    description: "Sales Manager",
    status: "Paused",
  },
  {
    key: "20",
    name: "Daniel Lewis",
    description: "DevOps Engineer",
    status: "Active",
  },
  {
    key: "21",
    name: "Amelia Clark",
    description: "Social Media Specialist",
    status: "Active",
  },
  {
    key: "22",
    name: "Jackson Walker",
    description: "Customer Support",
    status: "Active",
  },
  {
    key: "23",
    name: "Henry Hall",
    description: "Security Analyst",
    status: "Active",
  },
  {
    key: "24",
    name: "Charlotte Young",
    description: "PR Specialist",
    status: "Paused",
  },
  {
    key: "25",
    name: "Liam King",
    description: "Mobile App Developer",
    status: "Active",
  },
];
